CREATE DATABASE `504` /*!40100 DEFAULT CHARACTER SET utf8 */;
CREATE TABLE `contract_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `number` varchar(200) NOT NULL,
  `name` varchar(200) NOT NULL,
  `status` int(11) NOT NULL,
  `classification` int(11) NOT NULL,
  `leader` varchar(200) NOT NULL,
  `money` float NOT NULL,
  `needInvoice` int(11) NOT NULL,
  `filingTime` date DEFAULT NULL,
  `cdNumber` varchar(200) DEFAULT NULL,
  `requirementTimePlan` date NOT NULL,
  `requirementTimeReal` date DEFAULT NULL,
  `requirementPayMoney` float NOT NULL DEFAULT '0',
  `designTimePlan` date NOT NULL,
  `designTimeReal` date DEFAULT NULL,
  `designPayMoney` float DEFAULT '0',
  `testTimePlan` date NOT NULL,
  `testTimeReal` date DEFAULT NULL,
  `testPayMoney` float DEFAULT '0',
  `acceptanceTimePlan` date NOT NULL,
  `acceptanceTimeReal` date DEFAULT NULL,
  `acceptancePayMoney` float DEFAULT '0',
  `isDelay` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `contractNumber_UNIQUE` (`number`),
  UNIQUE KEY `contractName_UNIQUE` (`name`),
  KEY `idx_contract_info_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;
